In [1]:
import numpy as np

a = np.array([0,1,2,3])
b = np.atleast_2d(a)
b

array([[0, 1, 2, 3]])

In [3]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

covariance_matrix = np.cov(data, rowvar=False)

print(covariance_matrix)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [18]:
1 * 0.86**20

0.03875953108451433